#index:
#    path: /menu
#    controller: App\Controller\Menu::index

menu:
    path: /menu
    controller: App\Controller\MenuController::index

login:
    path: /login
    controller: App\Controller\LoginController::index

registration:
    path: /registration
    controller: App\Controller\RegistrationController::index
