#index:
#    path: /menu
#    controller: App\Controller\Menu::index

menu:
    path: /
    controller: App\Controller\MenuController::index

usersList:
    path: /users
    controller: App\Controller\ListOfUsersController::index

registration:
    path: /registration
    controller: App\Controller\RegistrationController::index


